on:
    push:
        branches:
            - '*'

name: Check Code Style

jobs:
    cs-check:
        uses: spiral/gh-actions/.github/workflows/cs.yml@master
        with:
            os: >-
                ['ubuntu-latest']
